using System;
using System.Collections.Generic;
using UnityEngine;

public static class RaptorNames
{
    public static string[] names =
    {
        "Chompers the Third",
        "Sancho",
        "Jacket",
        "Larry",
        "Sharpie",
        "Spike",
        "Spyro",
        "Blue",
        "Delta",
        "Echo",
        "Charlie",
        "Arlo",
        "Pervis",
        "Butch",
        "Bubbha",
        "Bak",
        "Lurleane",
        "Henry Stickmin",
        "Heathcliff",
        "Crisp Rat",
        "Charles",
        "Don Quixote",
        "Sans",
        "Steve",
        "John Raptor",
        "Pissbaby",
        "Ingebrigt",
        "Rapp",
        "Tor",
        "Kajsa",
        "Money D. Bags",
        "Julius",
        "Dino",
        "Clucky",
        "The Drink",
        "Grifdar",
        "Goku",
        "Foghorn Leghorn",
        "Hawk",
        "Tuah",
        "Donald",
        "Sproingus Boingus",
        "Bongbong",
        "Roland",
        "Bob",
        "Mac",
        "Tiphany",
        "Roadrunner",
        "Twilight Sparkle",
        "Leon",
        "Heihei",
        "Kylling",
        "Mike The Headless Chicken",
        "Gilgamesh, Destoryer of Worlds",
        "Chicka",
        "Astroid Destroyer",
        ""
    };
}
